### ISSUE TITLE
[CICD] Add premerge CI using github action

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids-container#12]
As container build does not require GPU resource, we could leverage github action resource to implement the premerge CI here

could refer to https://github.com/marketplace/actions/build-and-push-docker-images

and mark **push: false**
```
        name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: <some PR info>
```

and also https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
